# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:09
from __future__ import unicode_literals

import arenda.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=arenda.models.get_file_path, verbose_name='Файла')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Название типа', max_length=30, verbose_name='Название')),
                ('kind_plural', models.CharField(help_text='Название типа во множественном числе', max_length=30, verbose_name='Название во мн. ч.')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название помещения', max_length=100, verbose_name='Название')),
                ('area', models.FloatField(help_text='Площадь помещения', verbose_name='Площадь')),
                ('floor', models.PositiveSmallIntegerField(help_text='Этаж на котором расположено помещение', verbose_name='Этаж')),
                ('price', models.FloatField(help_text='Цена за квадратный метр', verbose_name='Цена за кв.м')),
                ('desc', models.TextField(help_text='Подробное описание', verbose_name='Описание')),
                ('active', models.BooleanField(default=True, help_text='Показывать помещение в списке', verbose_name='Показывать')),
                ('kinds', models.ManyToManyField(to='arenda.Kind', verbose_name='Типы помещений')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arenda.Place'),
        ),
    ]
