# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:18
from __future__ import unicode_literals

import arenda.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='kind',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Неактивная иконка'),
        ),
        migrations.AddField(
            model_name='kind',
            name='image_active',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Активная иконка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=arenda.models.get_file_path, verbose_name='Файл'),
        ),
    ]
